export default [
  {
    type: 'string',
    name: 'DZ',
    label: 'Algeria',
    title: 'Algeria',
    value: 'DZ',
  },
  {
    type: 'string',
    name: 'AS',
    label: 'American Samoa',
    title: 'American Samoa',
    value: 'AS',
  },
  {
    type: 'string',
    name: 'AD',
    label: 'AndorrA',
    title: 'AndorrA',
    value: 'AD',
  },

  {
    type: 'string',
    name: 'AI',
    label: 'Anguilla',
    title: 'Anguilla',
    value: 'AI',
  },
  {
    type: 'string',
    name: 'AQ',
    label: 'Antarctica',
    title: 'Antarctica',
    value: 'AQ',
  },
  {
    type: 'string',
    name: 'AG',
    label: 'Antigua and Barbuda',
    title: 'Antigua and Barbuda',
    value: 'AG',
  },
  {
    type: 'string',
    name: 'AR',
    label: 'Argentina',
    title: 'Argentina',
    value: 'AR',
  },
  {
    type: 'string',
    name: 'AM',
    label: 'Armenia',
    title: 'Armenia',
    value: 'AM',
  },
  { type: 'string', name: 'AW', label: 'Aruba', title: 'Aruba', value: 'AW' },
  {
    type: 'string',
    name: 'AU',
    label: 'Australia',
    title: 'Australia',
    value: 'AU',
  },
  {
    type: 'string',
    name: 'AT',
    label: 'Austria',
    title: 'Austria',
    value: 'AT',
  },
  {
    type: 'string',
    name: 'AZ',
    label: 'Azerbaijan',
    title: 'Azerbaijan',
    value: 'AZ',
  },
  {
    type: 'string',
    name: 'BS',
    label: 'Bahamas',
    title: 'Bahamas',
    value: 'BS',
  },
  {
    type: 'string',
    name: 'BH',
    label: 'Bahrain',
    title: 'Bahrain',
    value: 'BH',
  },
  {
    type: 'string',
    name: 'BD',
    label: 'Bangladesh',
    title: 'Bangladesh',
    value: 'BD',
  },
  {
    type: 'string',
    name: 'BB',
    label: 'Barbados',
    title: 'Barbados',
    value: 'BB',
  },
  {
    type: 'string',
    name: 'BY',
    label: 'Belarus',
    title: 'Belarus',
    value: 'BY',
  },
  {
    type: 'string',
    name: 'BE',
    label: 'Belgium',
    title: 'Belgium',
    value: 'BE',
  },
  { type: 'string', name: 'BZ', label: 'Belize', title: 'Belize', value: 'BZ' },
  { type: 'string', name: 'BJ', label: 'Benin', title: 'Benin', value: 'BJ' },
  {
    type: 'string',
    name: 'BM',
    label: 'Bermuda',
    title: 'Bermuda',
    value: 'BM',
  },
  { type: 'string', name: 'BT', label: 'Bhutan', title: 'Bhutan', value: 'BT' },
  {
    type: 'string',
    name: 'BO',
    label: 'Bolivia',
    title: 'Bolivia',
    value: 'BO',
  },
  {
    type: 'string',
    name: 'BA',
    label: 'Bosnia and Herzegovina',
    title: 'Bosnia and Herzegovina',
    value: 'BA',
  },
  {
    type: 'string',
    name: 'BW',
    label: 'Botswana',
    title: 'Botswana',
    value: 'BW',
  },
  {
    type: 'string',
    name: 'BV',
    label: 'Bouvet Island',
    title: 'Bouvet Island',
    value: 'BV',
  },
  { type: 'string', name: 'BR', label: 'Brazil', title: 'Brazil', value: 'BR' },
  {
    type: 'string',
    name: 'IO',
    label: 'British Indian Ocean Territory',
    title: 'British Indian Ocean Territory',
    value: 'IO',
  },
  {
    type: 'string',
    name: 'BN',
    label: 'Brunei Darussalam',
    title: 'Brunei Darussalam',
    value: 'BN',
  },
  {
    type: 'string',
    name: 'BG',
    label: 'Bulgaria',
    title: 'Bulgaria',
    value: 'BG',
  },
  {
    type: 'string',
    name: 'BF',
    label: 'Burkina Faso',
    title: 'Burkina Faso',
    value: 'BF',
  },
  {
    type: 'string',
    name: 'BI',
    label: 'Burundi',
    title: 'Burundi',
    value: 'BI',
  },
  {
    type: 'string',
    name: 'KH',
    label: 'Cambodia',
    title: 'Cambodia',
    value: 'KH',
  },
  {
    type: 'string',
    name: 'CM',
    label: 'Cameroon',
    title: 'Cameroon',
    value: 'CM',
  },
  { type: 'string', name: 'CA', label: 'Canada', title: 'Canada', value: 'CA' },
  {
    type: 'string',
    name: 'CV',
    label: 'Cape Verde',
    title: 'Cape Verde',
    value: 'CV',
  },
  {
    type: 'string',
    name: 'KY',
    label: 'Cayman Islands',
    title: 'Cayman Islands',
    value: 'KY',
  },
  {
    type: 'string',
    name: 'CF',
    label: 'Central African Republic',
    title: 'Central African Republic',
    value: 'CF',
  },
  { type: 'string', name: 'TD', label: 'Chad', title: 'Chad', value: 'TD' },
  { type: 'string', name: 'CL', label: 'Chile', title: 'Chile', value: 'CL' },
  { type: 'string', name: 'CN', label: 'China', title: 'China', value: 'CN' },
  {
    type: 'string',
    name: 'CX',
    label: 'Christmas Island',
    title: 'Christmas Island',
    value: 'CX',
  },
  {
    type: 'string',
    name: 'CC',
    label: 'Cocos (Keeling) Islands',
    title: 'Cocos (Keeling) Islands',
    value: 'CC',
  },
  {
    type: 'string',
    name: 'CO',
    label: 'Colombia',
    title: 'Colombia',
    value: 'CO',
  },
  {
    type: 'string',
    name: 'KM',
    label: 'Comoros',
    title: 'Comoros',
    value: 'KM',
  },
  { type: 'string', name: 'CG', label: 'Congo', title: 'Congo', value: 'CG' },
  {
    type: 'string',
    name: 'CD',
    label: 'Democratic Republic of the Congo',
    title: 'Democratic Republic of the Congo',
    value: 'CD',
  },
  {
    type: 'string',
    name: 'CK',
    label: 'Cook Islands',
    title: 'Cook Islands',
    value: 'CK',
  },
  {
    type: 'string',
    name: 'CR',
    label: 'Costa Rica',
    title: 'Costa Rica',
    value: 'CR',
  },
  {
    type: 'string',
    name: 'CI',
    label: "Cote D'Ivoire",
    title: "Cote D'Ivoire",
    value: 'CI',
  },
  {
    type: 'string',
    name: 'HR',
    label: 'Croatia',
    title: 'Croatia',
    value: 'HR',
  },
  { type: 'string', name: 'CU', label: 'Cuba', title: 'Cuba', value: 'CU' },
  { type: 'string', name: 'CY', label: 'Cyprus', title: 'Cyprus', value: 'CY' },
  {
    type: 'string',
    name: 'CZ',
    label: 'Czech Republic',
    title: 'Czech Republic',
    value: 'CZ',
  },
  {
    type: 'string',
    name: 'DK',
    label: 'Denmark',
    title: 'Denmark',
    value: 'DK',
  },
  {
    type: 'string',
    name: 'DJ',
    label: 'Djibouti',
    title: 'Djibouti',
    value: 'DJ',
  },
  {
    type: 'string',
    name: 'DM',
    label: 'Dominica',
    title: 'Dominica',
    value: 'DM',
  },
  {
    type: 'string',
    name: 'DO',
    label: 'Dominican Republic',
    title: 'Dominican Republic',
    value: 'DO',
  },
  {
    type: 'string',
    name: 'EC',
    label: 'Ecuador',
    title: 'Ecuador',
    value: 'EC',
  },
  { type: 'string', name: 'EG', label: 'Egypt', title: 'Egypt', value: 'EG' },
  {
    type: 'string',
    name: 'SV',
    label: 'El Salvador',
    title: 'El Salvador',
    value: 'SV',
  },
  {
    type: 'string',
    name: 'GQ',
    label: 'Equatorial Guinea',
    title: 'Equatorial Guinea',
    value: 'GQ',
  },
  {
    type: 'string',
    name: 'ER',
    label: 'Eritrea',
    title: 'Eritrea',
    value: 'ER',
  },
  {
    type: 'string',
    name: 'EE',
    label: 'Estonia',
    title: 'Estonia',
    value: 'EE',
  },
  {
    type: 'string',
    name: 'ET',
    label: 'Ethiopia',
    title: 'Ethiopia',
    value: 'ET',
  },
  {
    type: 'string',
    name: 'FK',
    label: 'Falkland Islands (Malvinas)',
    title: 'Falkland Islands (Malvinas)',
    value: 'FK',
  },
  {
    type: 'string',
    name: 'FO',
    label: 'Faroe Islands',
    title: 'Faroe Islands',
    value: 'FO',
  },
  { type: 'string', name: 'FJ', label: 'Fiji', title: 'Fiji', value: 'FJ' },
  {
    type: 'string',
    name: 'FI',
    label: 'Finland',
    title: 'Finland',
    value: 'FI',
  },
  { type: 'string', name: 'FR', label: 'France', title: 'France', value: 'FR' },
  {
    type: 'string',
    name: 'GF',
    label: 'French Guiana',
    title: 'French Guiana',
    value: 'GF',
  },
  {
    type: 'string',
    name: 'PF',
    label: 'French Polynesia',
    title: 'French Polynesia',
    value: 'PF',
  },
  {
    type: 'string',
    name: 'TF',
    label: 'French Southern Territories',
    title: 'French Southern Territories',
    value: 'TF',
  },
  { type: 'string', name: 'GA', label: 'Gabon', title: 'Gabon', value: 'GA' },
  { type: 'string', name: 'GM', label: 'Gambia', title: 'Gambia', value: 'GM' },
  {
    type: 'string',
    name: 'GE',
    label: 'Georgia',
    title: 'Georgia',
    value: 'GE',
  },
  {
    type: 'string',
    name: 'DE',
    label: 'Germany',
    title: 'Germany',
    value: 'DE',
  },
  { type: 'string', name: 'GH', label: 'Ghana', title: 'Ghana', value: 'GH' },
  {
    type: 'string',
    name: 'GI',
    label: 'Gibraltar',
    title: 'Gibraltar',
    value: 'GI',
  },
  { type: 'string', name: 'GR', label: 'Greece', title: 'Greece', value: 'GR' },
  {
    type: 'string',
    name: 'GL',
    label: 'Greenland',
    title: 'Greenland',
    value: 'GL',
  },
  {
    type: 'string',
    name: 'GD',
    label: 'Grenada',
    title: 'Grenada',
    value: 'GD',
  },
  {
    type: 'string',
    name: 'GP',
    label: 'Guadeloupe',
    title: 'Guadeloupe',
    value: 'GP',
  },
  { type: 'string', name: 'GU', label: 'Guam', title: 'Guam', value: 'GU' },
  {
    type: 'string',
    name: 'GT',
    label: 'Guatemala',
    title: 'Guatemala',
    value: 'GT',
  },
  {
    type: 'string',
    name: 'GG',
    label: 'Guernsey',
    title: 'Guernsey',
    value: 'GG',
  },
  { type: 'string', name: 'GN', label: 'Guinea', title: 'Guinea', value: 'GN' },
  {
    type: 'string',
    name: 'GW',
    label: 'Guinea-Bissau',
    title: 'Guinea-Bissau',
    value: 'GW',
  },
  { type: 'string', name: 'GY', label: 'Guyana', title: 'Guyana', value: 'GY' },
  { type: 'string', name: 'HT', label: 'Haiti', title: 'Haiti', value: 'HT' },
  {
    type: 'string',
    name: 'HM',
    label: 'Heard Island and Mcdonald Islands',
    title: 'Heard Island and Mcdonald Islands',
    value: 'HM',
  },
  {
    type: 'string',
    name: 'VA',
    label: 'Holy See (Vatican City State)',
    title: 'Holy See (Vatican City State)',
    value: 'VA',
  },
  {
    type: 'string',
    name: 'HN',
    label: 'Honduras',
    title: 'Honduras',
    value: 'HN',
  },
  {
    type: 'string',
    name: 'HK',
    label: 'Hong Kong',
    title: 'Hong Kong',
    value: 'HK',
  },
  {
    type: 'string',
    name: 'HU',
    label: 'Hungary',
    title: 'Hungary',
    value: 'HU',
  },
  {
    type: 'string',
    name: 'IS',
    label: 'Iceland',
    title: 'Iceland',
    value: 'IS',
  },
  { type: 'string', name: 'IN', label: 'India', title: 'India', value: 'IN' },
  {
    type: 'string',
    name: 'ID',
    label: 'Indonesia',
    title: 'Indonesia',
    value: 'ID',
  },
  {
    type: 'string',
    name: 'IR',
    label: 'Iran',
    title: 'Iran',
    value: 'IR',
  },
  { type: 'string', name: 'IQ', label: 'Iraq', title: 'Iraq', value: 'IQ' },
  {
    type: 'string',
    name: 'IE',
    label: 'Ireland',
    title: 'Ireland',
    value: 'IE',
  },
  {
    type: 'string',
    name: 'IM',
    label: 'Isle of Man',
    title: 'Isle of Man',
    value: 'IM',
  },
  { type: 'string', name: 'IL', label: 'Israel', title: 'Israel', value: 'IL' },
  { type: 'string', name: 'IT', label: 'Italy', title: 'Italy', value: 'IT' },
  {
    type: 'string',
    name: 'JM',
    label: 'Jamaica',
    title: 'Jamaica',
    value: 'JM',
  },
  { type: 'string', name: 'JP', label: 'Japan', title: 'Japan', value: 'JP' },
  { type: 'string', name: 'JE', label: 'Jersey', title: 'Jersey', value: 'JE' },
  { type: 'string', name: 'JO', label: 'Jordan', title: 'Jordan', value: 'JO' },
  {
    type: 'string',
    name: 'KZ',
    label: 'Kazakhstan',
    title: 'Kazakhstan',
    value: 'KZ',
  },
  { type: 'string', name: 'KE', label: 'Kenya', title: 'Kenya', value: 'KE' },
  {
    type: 'string',
    name: 'KI',
    label: 'Kiribati',
    title: 'Kiribati',
    value: 'KI',
  },
  {
    type: 'string',
    name: 'XK',
    label: 'Kosovo',
    title: 'Kosovo',
    value: 'XK',
  },
  {
    type: 'string',
    name: 'KP',
    label: "Korea, Democratic People's Republic of",
    title: "Korea, Democratic People's Republic of",
    value: 'KP',
  },
  {
    type: 'string',
    name: 'KR',
    label: 'Republic of Korea',
    title: 'Republic of Korea',
    value: 'KR',
  },
  { type: 'string', name: 'KW', label: 'Kuwait', title: 'Kuwait', value: 'KW' },
  {
    type: 'string',
    name: 'KG',
    label: 'Kyrgyzstan',
    title: 'Kyrgyzstan',
    value: 'KG',
  },
  {
    type: 'string',
    name: 'LA',
    label: "Lao People's Democratic Republic",
    title: "Lao People's Democratic Republic",
    value: 'LA',
  },
  { type: 'string', name: 'LV', label: 'Latvia', title: 'Latvia', value: 'LV' },
  {
    type: 'string',
    name: 'LB',
    label: 'Lebanon',
    title: 'Lebanon',
    value: 'LB',
  },
  {
    type: 'string',
    name: 'LS',
    label: 'Lesotho',
    title: 'Lesotho',
    value: 'LS',
  },
  {
    type: 'string',
    name: 'LR',
    label: 'Liberia',
    title: 'Liberia',
    value: 'LR',
  },
  {
    type: 'string',
    name: 'LY',
    label: 'Libyan Arab Jamahiriya',
    title: 'Libyan Arab Jamahiriya',
    value: 'LY',
  },
  {
    type: 'string',
    name: 'LI',
    label: 'Liechtenstein',
    title: 'Liechtenstein',
    value: 'LI',
  },
  {
    type: 'string',
    name: 'LT',
    label: 'Lithuania',
    title: 'Lithuania',
    value: 'LT',
  },
  {
    type: 'string',
    name: 'LU',
    label: 'Luxembourg',
    title: 'Luxembourg',
    value: 'LU',
  },
  { type: 'string', name: 'MO', label: 'Macao', title: 'Macao', value: 'MO' },
  {
    type: 'string',
    name: 'MK',
    label: 'Macedonia, The Former Yugoslav Republic of',
    title: 'Macedonia, The Former Yugoslav Republic of',
    value: 'MK',
  },
  {
    type: 'string',
    name: 'MG',
    label: 'Madagascar',
    title: 'Madagascar',
    value: 'MG',
  },
  { type: 'string', name: 'MW', label: 'Malawi', title: 'Malawi', value: 'MW' },
  {
    type: 'string',
    name: 'MY',
    label: 'Malaysia',
    title: 'Malaysia',
    value: 'MY',
  },
  {
    type: 'string',
    name: 'MV',
    label: 'Maldives',
    title: 'Maldives',
    value: 'MV',
  },
  { type: 'string', name: 'ML', label: 'Mali', title: 'Mali', value: 'ML' },
  { type: 'string', name: 'MT', label: 'Malta', title: 'Malta', value: 'MT' },
  {
    type: 'string',
    name: 'MH',
    label: 'Marshall Islands',
    title: 'Marshall Islands',
    value: 'MH',
  },
  {
    type: 'string',
    name: 'MQ',
    label: 'Martinique',
    title: 'Martinique',
    value: 'MQ',
  },
  {
    type: 'string',
    name: 'MF',
    label: 'Saint-Martin',
    title: 'Saint-Martin',
    value: 'MF',
  },
  {
    type: 'string',
    name: 'MR',
    label: 'Mauritania',
    title: 'Mauritania',
    value: 'MR',
  },
  {
    type: 'string',
    name: 'MU',
    label: 'Mauritius',
    title: 'Mauritius',
    value: 'MU',
  },
  {
    type: 'string',
    name: 'YT',
    label: 'Mayotte',
    title: 'Mayotte',
    value: 'YT',
  },
  { type: 'string', name: 'MX', label: 'Mexico', title: 'Mexico', value: 'MX' },
  {
    type: 'string',
    name: 'FM',
    label: 'Micronesia, Federated States of',
    title: 'Micronesia, Federated States of',
    value: 'FM',
  },
  {
    type: 'string',
    name: 'MD',
    label: 'Moldova, Republic of',
    title: 'Moldova, Republic of',
    value: 'MD',
  },
  { type: 'string', name: 'MC', label: 'Monaco', title: 'Monaco', value: 'MC' },
  {
    type: 'string',
    name: 'MN',
    label: 'Mongolia',
    title: 'Mongolia',
    value: 'MN',
  },
  {
    type: 'string',
    name: 'MS',
    label: 'Montserrat',
    title: 'Montserrat',
    value: 'MS',
  },
  {
    type: 'string',
    name: 'MA',
    label: 'Morocco',
    title: 'Morocco',
    value: 'MA',
  },
  {
    type: 'string',
    name: 'MZ',
    label: 'Mozambique',
    title: 'Mozambique',
    value: 'MZ',
  },
  {
    type: 'string',
    name: 'MM',
    label: 'Myanmar',
    title: 'Myanmar',
    value: 'MM',
  },
  {
    type: 'string',
    name: 'NA',
    label: 'Namibia',
    title: 'Namibia',
    value: 'NA',
  },
  { type: 'string', name: 'NR', label: 'Nauru', title: 'Nauru', value: 'NR' },
  { type: 'string', name: 'NP', label: 'Nepal', title: 'Nepal', value: 'NP' },
  {
    type: 'string',
    name: 'NL',
    label: 'Netherlands',
    title: 'Netherlands',
    value: 'NL',
  },
  {
    type: 'string',
    name: 'AN',
    label: 'Netherlands Antilles',
    title: 'Netherlands Antilles',
    value: 'AN',
  },
  {
    type: 'string',
    name: 'NC',
    label: 'New Caledonia',
    title: 'New Caledonia',
    value: 'NC',
  },
  {
    type: 'string',
    name: 'NZ',
    label: 'New Zealand',
    title: 'New Zealand',
    value: 'NZ',
  },
  {
    type: 'string',
    name: 'NI',
    label: 'Nicaragua',
    title: 'Nicaragua',
    value: 'NI',
  },
  { type: 'string', name: 'NE', label: 'Niger', title: 'Niger', value: 'NE' },
  {
    type: 'string',
    name: 'NG',
    label: 'Nigeria',
    title: 'Nigeria',
    value: 'NG',
  },
  { type: 'string', name: 'NU', label: 'Niue', title: 'Niue', value: 'NU' },
  {
    type: 'string',
    name: 'NF',
    label: 'Norfolk Island',
    title: 'Norfolk Island',
    value: 'NF',
  },
  {
    type: 'string',
    name: 'MP',
    label: 'Northern Mariana Islands',
    title: 'Northern Mariana Islands',
    value: 'MP',
  },
  { type: 'string', name: 'NO', label: 'Norway', title: 'Norway', value: 'NO' },
  { type: 'string', name: 'OM', label: 'Oman', title: 'Oman', value: 'OM' },
  {
    type: 'string',
    name: 'PK',
    label: 'Pakistan',
    title: 'Pakistan',
    value: 'PK',
  },
  { type: 'string', name: 'PW', label: 'Palau', title: 'Palau', value: 'PW' },
  {
    type: 'string',
    name: 'PS',
    label: 'Palestinian Territory, Occupied',
    title: 'Palestinian Territory, Occupied',
    value: 'PS',
  },
  { type: 'string', name: 'PA', label: 'Panama', title: 'Panama', value: 'PA' },
  {
    type: 'string',
    name: 'PG',
    label: 'Papua New Guinea',
    title: 'Papua New Guinea',
    value: 'PG',
  },
  {
    type: 'string',
    name: 'PY',
    label: 'Paraguay',
    title: 'Paraguay',
    value: 'PY',
  },
  { type: 'string', name: 'PE', label: 'Peru', title: 'Peru', value: 'PE' },
  {
    type: 'string',
    name: 'PH',
    label: 'Philippines',
    title: 'Philippines',
    value: 'PH',
  },
  {
    type: 'string',
    name: 'PN',
    label: 'Pitcairn',
    title: 'Pitcairn',
    value: 'PN',
  },
  { type: 'string', name: 'PL', label: 'Poland', title: 'Poland', value: 'PL' },
  {
    type: 'string',
    name: 'PT',
    label: 'Portugal',
    title: 'Portugal',
    value: 'PT',
  },
  {
    type: 'string',
    name: 'PR',
    label: 'Puerto Rico',
    title: 'Puerto Rico',
    value: 'PR',
  },
  { type: 'string', name: 'QA', label: 'Qatar', title: 'Qatar', value: 'QA' },
  {
    type: 'string',
    name: 'RE',
    label: 'Reunion',
    title: 'Reunion',
    value: 'RE',
  },
  {
    type: 'string',
    name: 'RO',
    label: 'Romania',
    title: 'Romania',
    value: 'RO',
  },
  {
    type: 'string',
    name: 'RU',
    label: 'Russian Federation',
    title: 'Russian Federation',
    value: 'RU',
  },
  { type: 'string', name: 'RW', label: 'RWANDA', title: 'RWANDA', value: 'RW' },
  {
    type: 'string',
    name: 'SH',
    label: 'Saint Helena',
    title: 'Saint Helena',
    value: 'SH',
  },
  {
    type: 'string',
    name: 'KN',
    label: 'Saint Kitts and Nevis',
    title: 'Saint Kitts and Nevis',
    value: 'KN',
  },
  {
    type: 'string',
    name: 'LC',
    label: 'Saint Lucia',
    title: 'Saint Lucia',
    value: 'LC',
  },
  {
    type: 'string',
    name: 'PM',
    label: 'Saint Pierre and Miquelon',
    title: 'Saint Pierre and Miquelon',
    value: 'PM',
  },
  {
    type: 'string',
    name: 'BL',
    label: 'Saint Barthélemy',
    title: 'Saint Barthélemy',
    value: 'BL',
  },
  {
    type: 'string',
    name: 'VC',
    label: 'Saint Vincent and the Grenadines',
    title: 'Saint Vincent and the Grenadines',
    value: 'VC',
  },
  { type: 'string', name: 'WS', label: 'Samoa', title: 'Samoa', value: 'WS' },
  {
    type: 'string',
    name: 'SM',
    label: 'San Marino',
    title: 'San Marino',
    value: 'SM',
  },
  {
    type: 'string',
    name: 'ST',
    label: 'Sao Tome and Principe',
    title: 'Sao Tome and Principe',
    value: 'ST',
  },
  {
    type: 'string',
    name: 'SA',
    label: 'Saudi Arabia',
    title: 'Saudi Arabia',
    value: 'SA',
  },
  {
    type: 'string',
    name: 'SN',
    label: 'Senegal',
    title: 'Senegal',
    value: 'SN',
  },
  {
    type: 'string',
    name: 'CS',
    label: 'Serbia and Montenegro',
    title: 'Serbia and Montenegro',
    value: 'CS',
  },
  {
    type: 'string',
    name: 'SC',
    label: 'Seychelles',
    title: 'Seychelles',
    value: 'SC',
  },
  {
    type: 'string',
    name: 'SL',
    label: 'Sierra Leone',
    title: 'Sierra Leone',
    value: 'SL',
  },
  {
    type: 'string',
    name: 'SG',
    label: 'Singapore',
    title: 'Singapore',
    value: 'SG',
  },
  {
    type: 'string',
    name: 'SK',
    label: 'Slovakia',
    title: 'Slovakia',
    value: 'SK',
  },
  {
    type: 'string',
    name: 'SI',
    label: 'Slovenia',
    title: 'Slovenia',
    value: 'SI',
  },
  {
    type: 'string',
    name: 'SB',
    label: 'Solomon Islands',
    title: 'Solomon Islands',
    value: 'SB',
  },
  {
    type: 'string',
    name: 'SO',
    label: 'Somalia',
    title: 'Somalia',
    value: 'SO',
  },
  {
    type: 'string',
    name: 'ZA',
    label: 'South Africa',
    title: 'South Africa',
    value: 'ZA',
  },
  {
    type: 'string',
    name: 'GS',
    label: 'South Georgia and the South Sandwich Islands',
    title: 'South Georgia and the South Sandwich Islands',
    value: 'GS',
  },
  { type: 'string', name: 'ES', label: 'Spain', title: 'Spain', value: 'ES' },
  {
    type: 'string',
    name: 'LK',
    label: 'Sri Lanka',
    title: 'Sri Lanka',
    value: 'LK',
  },
  { type: 'string', name: 'SD', label: 'Sudan', title: 'Sudan', value: 'SD' },
  {
    type: 'string',
    name: 'SS',
    label: 'South Sudan',
    title: 'South Sudan',
    value: 'SS',
  },
  {
    type: 'string',
    name: 'SR',
    label: 'Suriname',
    title: 'Suriname',
    value: 'SR',
  },
  {
    type: 'string',
    name: 'SJ',
    label: 'Svalbard and Jan Mayen',
    title: 'Svalbard and Jan Mayen',
    value: 'SJ',
  },
  {
    type: 'string',
    name: 'SZ',
    label: 'Swaziland',
    title: 'Swaziland',
    value: 'SZ',
  },
  { type: 'string', name: 'SE', label: 'Sweden', title: 'Sweden', value: 'SE' },
  {
    type: 'string',
    name: 'CH',
    label: 'Switzerland',
    title: 'Switzerland',
    value: 'CH',
  },
  {
    type: 'string',
    name: 'SY',
    label: 'Syrian Arab Republic',
    title: 'Syrian Arab Republic',
    value: 'SY',
  },
  { type: 'string', name: 'TW', label: 'Taiwan', title: 'Taiwan', value: 'TW' },
  {
    type: 'string',
    name: 'TJ',
    label: 'Tajikistan',
    title: 'Tajikistan',
    value: 'TJ',
  },
  {
    type: 'string',
    name: 'TZ',
    label: 'Tanzania, United Republic of',
    title: 'Tanzania, United Republic of',
    value: 'TZ',
  },
  {
    type: 'string',
    name: 'TH',
    label: 'Thailand',
    title: 'Thailand',
    value: 'TH',
  },
  {
    type: 'string',
    name: 'TL',
    label: 'Timor-Leste',
    title: 'Timor-Leste',
    value: 'TL',
  },
  { type: 'string', name: 'TG', label: 'Togo', title: 'Togo', value: 'TG' },
  {
    type: 'string',
    name: 'TK',
    label: 'Tokelau',
    title: 'Tokelau',
    value: 'TK',
  },
  { type: 'string', name: 'TO', label: 'Tonga', title: 'Tonga', value: 'TO' },
  {
    type: 'string',
    name: 'TT',
    label: 'Trinidad and Tobago',
    title: 'Trinidad and Tobago',
    value: 'TT',
  },
  {
    type: 'string',
    name: 'TN',
    label: 'Tunisia',
    title: 'Tunisia',
    value: 'TN',
  },
  { type: 'string', name: 'TR', label: 'Turkey', title: 'Turkey', value: 'TR' },
  {
    type: 'string',
    name: 'TM',
    label: 'Turkmenistan',
    title: 'Turkmenistan',
    value: 'TM',
  },
  {
    type: 'string',
    name: 'TC',
    label: 'Turks and Caicos Islands',
    title: 'Turks and Caicos Islands',
    value: 'TC',
  },
  { type: 'string', name: 'TV', label: 'Tuvalu', title: 'Tuvalu', value: 'TV' },
  { type: 'string', name: 'UG', label: 'Uganda', title: 'Uganda', value: 'UG' },
  {
    type: 'string',
    name: 'UA',
    label: 'Ukraine',
    title: 'Ukraine',
    value: 'UA',
  },
  {
    type: 'string',
    name: 'AE',
    label: 'United Arab Emirates',
    title: 'United Arab Emirates',
    value: 'AE',
  },
  {
    type: 'string',
    name: 'GB',
    label: 'United Kingdom',
    title: 'United Kingdom',
    value: 'GB',
  },
  {
    type: 'string',
    name: 'US',
    label: 'United States',
    title: 'United States',
    value: 'US',
  },
  {
    type: 'string',
    name: 'UM',
    label: 'United States Minor Outlying Islands',
    title: 'United States Minor Outlying Islands',
    value: 'UM',
  },
  {
    type: 'string',
    name: 'UY',
    label: 'Uruguay',
    title: 'Uruguay',
    value: 'UY',
  },
  {
    type: 'string',
    name: 'UZ',
    label: 'Uzbekistan',
    title: 'Uzbekistan',
    value: 'UZ',
  },
  {
    type: 'string',
    name: 'VU',
    label: 'Vanuatu',
    title: 'Vanuatu',
    value: 'VU',
  },
  {
    type: 'string',
    name: 'VE',
    label: 'Venezuela',
    title: 'Venezuela',
    value: 'VE',
  },
  {
    type: 'string',
    name: 'VN',
    label: 'Viet Nam',
    title: 'Viet Nam',
    value: 'VN',
  },
  {
    type: 'string',
    name: 'VG',
    label: 'Virgin Islands, British',
    title: 'Virgin Islands, British',
    value: 'VG',
  },
  {
    type: 'string',
    name: 'VI',
    label: 'Virgin Islands, U.S.',
    title: 'Virgin Islands, U.S.',
    value: 'VI',
  },
  {
    type: 'string',
    name: 'WF',
    label: 'Wallis and Futuna',
    title: 'Wallis and Futuna',
    value: 'WF',
  },
  {
    type: 'string',
    name: 'EH',
    label: 'Western Sahara',
    title: 'Western Sahara',
    value: 'EH',
  },
  { type: 'string', name: 'YE', label: 'Yemen', title: 'Yemen', value: 'YE' },
  { type: 'string', name: 'ZM', label: 'Zambia', title: 'Zambia', value: 'ZM' },
  {
    type: 'string',
    name: 'ZW',
    label: 'Zimbabwe',
    title: 'Zimbabwe',
    value: 'ZW',
  },
];
